### ISSUE TITLE
GSoC人大

### ISSUE THREAD

**Issue by yihui** [yihui/ideas#30]
# GSoC经历介绍

2011年假期参加GSoC, 让我着实体验了一个R包程序是如何由最初的直接易懂到最终连帮助文档都略显晦涩的全过程, 这也让我在R语言和编程细节上都收获颇丰, 特别是注意到他们对模拟结果可重复性的重视程度. 在此我只介绍自己申请GSoC的经历, 因为一来不同项目由于导师或团队不同, 项目的进行方式会有很大不同, 二来只要能保持申请项目时的积极态度, 很好地完成项目一定不是问题. 

项目申请关键在于和导师的积极交流, 把要申请的项目当成自己已经在做的项目来与导师讨论, 对项目要有自己的看法和建议, 这是必须而且应该是理所当然的, 因为你决定申请的项目必然是你自己有想法有兴趣的.  我比较走运, 做的是EM算法收敛相关的项目, 本科时学的还算比较认真, 正好我的毕业论文也与之有关. 在做论文时就感觉到EM加速收敛的重要性, 看完项目简介后我又尝试了下导师自己写的加速EM迭代的R包SQUAREM, 并在试用中发现了其中的一个小bug. 得到导师的认可后, 还需要一份好的proposal, 提交proposal有一周时间. 但对于势在必得的人, 这一周不应是完成proposal的最后期限, 而是根据众导师意见不断完善自己proposal的迭代过程. 关于Deadline, gsoc指南上有句话: This will come sooner than you think. 这让像我这样拖沓的人受用一生, 在此分享给大家, 并祝有志于参加GSoC感受开源社区的统计学院同学们都能有自己独特的收获, 共同让人大统计通过GSoC R Project for Statistical Computing扬名海外!

赵辉

**Comment by yanping** [comment]
赵辉是谁？他写的？

**Comment by yihui** [comment]
人大学生。大四的时候和怡轩参加了GSoC：
http://www.google-melange.com/gsoc/project/google/gsoc2011/hynux/21001

我请他们几个参加GSoC的人写一点经验在人大分享一下。
